use std::collections::{BTreeMap, BTreeSet};
use std::io::{Cursor, Read};

use zip::{CompressionMethod, ZipArchive};

use document_ir::MediaTypeIr;

use crate::image::validate_image;
use crate::xml::{XmlNode, parse_xml};
use crate::{DocxError, DocxLimit, DocxLimits, DocxValidationError};

const CONTENT_TYPES_NS: &str = "http://schemas.openxmlformats.org/package/2006/content-types";
const PACKAGE_RELS_NS: &str = "http://schemas.openxmlformats.org/package/2006/relationships";
const WORD_NS: &str = "http://schemas.openxmlformats.org/wordprocessingml/2006/main";
const OFFICE_DOCUMENT_REL: &str =
    "http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument";
const IMAGE_REL: &str = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/image";
const MAIN_CONTENT_TYPE: &str =
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml";
const DRAWING_REL_NS: &str = "http://schemas.openxmlformats.org/officeDocument/2006/relationships";
const WORD_DRAWING_NS: &str =
    "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing";
const DRAWING_NS: &str = "http://schemas.openxmlformats.org/drawingml/2006/main";
const PICTURE_NS: &str = "http://schemas.openxmlformats.org/drawingml/2006/picture";
const OFFICE_MATH_NS: &str = "http://schemas.openxmlformats.org/officeDocument/2006/math";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct DocxValidator {
    limits: DocxLimits,
}

impl DocxValidator {
    pub const fn new(limits: DocxLimits) -> Self {
        Self { limits }
    }

    pub const fn limits(&self) -> &DocxLimits {
        &self.limits
    }

    /// Validates only the deterministic subset generated by this crate.
    pub fn validate(&self, bytes: &[u8]) -> Result<(), DocxValidationError> {
        if u64::try_from(bytes.len()).unwrap_or(u64::MAX) > self.limits.max_output_bytes {
            return Err(DocxValidationError::LimitExceeded(DocxLimit::OutputBytes));
        }
        let parts = self.read_parts(bytes)?;
        for required in ["[Content_Types].xml", "_rels/.rels", "word/document.xml"] {
            if !parts.contains_key(required) {
                return Err(DocxValidationError::MissingRequiredPart);
            }
        }
        let mut media = BTreeMap::new();
        for (name, value) in &parts {
            if let Some(media_type) = media_part_type(name) {
                media.insert(name.clone(), media_type);
                validate_image(value, media_type, &self.limits).map_err(|error| {
                    if let DocxError::LimitExceeded(limit) = error {
                        DocxValidationError::LimitExceeded(limit)
                    } else {
                        DocxValidationError::ImageMismatch
                    }
                })?;
            } else if !matches!(
                name.as_str(),
                "[Content_Types].xml"
                    | "_rels/.rels"
                    | "word/document.xml"
                    | "word/_rels/document.xml.rels"
            ) {
                return Err(classify_unexpected(name));
            }
        }
        if media.len() > self.limits.max_images {
            return Err(DocxValidationError::LimitExceeded(DocxLimit::Images));
        }
        if media.is_empty() && parts.contains_key("word/_rels/document.xml.rels") {
            return Err(DocxValidationError::UnexpectedPart);
        }
        let xml_bytes = parts
            .iter()
            .filter(|(name, _)| media_part_type(name).is_none())
            .try_fold(0_u64, |total, (_, value)| {
                total
                    .checked_add(u64::try_from(value.len()).unwrap_or(u64::MAX))
                    .ok_or(DocxValidationError::LimitExceeded(DocxLimit::XmlBytes))
            })?;
        if xml_bytes > self.limits.max_xml_bytes {
            return Err(DocxValidationError::LimitExceeded(DocxLimit::XmlBytes));
        }
        let total_asset_bytes = media.keys().try_fold(0_u64, |total, name| {
            total
                .checked_add(u64::try_from(parts[name].len()).unwrap_or(u64::MAX))
                .ok_or(DocxValidationError::LimitExceeded(
                    DocxLimit::TotalAssetBytes,
                ))
        })?;
        if total_asset_bytes > self.limits.max_total_asset_bytes {
            return Err(DocxValidationError::LimitExceeded(
                DocxLimit::TotalAssetBytes,
            ));
        }
        validate_content_types(
            parse_xml(&parts["[Content_Types].xml"], &self.limits)?,
            &media,
        )?;
        validate_root_relationships(parse_xml(&parts["_rels/.rels"], &self.limits)?)?;
        let relationships = match parts.get("word/_rels/document.xml.rels") {
            Some(bytes) => validate_document_relationships(
                parse_xml(bytes, &self.limits)?,
                parts.keys().map(String::as_str).collect(),
            )?,
            None if media.is_empty() => BTreeMap::new(),
            None => return Err(DocxValidationError::MissingRequiredPart),
        };
        if relationships.len() != media.len()
            || relationships.values().collect::<BTreeSet<_>>()
                != media.keys().collect::<BTreeSet<_>>()
        {
            return Err(DocxValidationError::ImageMismatch);
        }
        let references = validate_document(
            parse_xml(&parts["word/document.xml"], &self.limits)?,
            !media.is_empty(),
            &self.limits,
        )?;
        if references.len() != relationships.len()
            || references
                .iter()
                .any(|reference| !relationships.contains_key(reference))
        {
            return Err(DocxValidationError::ImageMismatch);
        }
        Ok(())
    }

    fn read_parts(&self, bytes: &[u8]) -> Result<BTreeMap<String, Vec<u8>>, DocxValidationError> {
        let mut archive =
            ZipArchive::new(Cursor::new(bytes)).map_err(|_| DocxValidationError::InvalidZip)?;
        if archive.len() > self.limits.max_entries {
            return Err(DocxValidationError::LimitExceeded(DocxLimit::Entries));
        }
        let mut exact = BTreeSet::new();
        let mut folded = BTreeSet::new();
        let mut total = 0_u64;
        let mut parts = BTreeMap::new();
        for index in 0..archive.len() {
            let mut entry = archive
                .by_index(index)
                .map_err(|_| DocxValidationError::InvalidZip)?;
            let name = validate_part_name(entry.name(), &self.limits)?;
            if !exact.insert(name.clone()) || !folded.insert(name.to_ascii_lowercase()) {
                return Err(DocxValidationError::DuplicatePart);
            }
            if entry.is_symlink() {
                return Err(DocxValidationError::SymlinkPart);
            }
            if entry.encrypted() {
                return Err(DocxValidationError::EncryptedPart);
            }
            if entry.is_dir() {
                return Err(DocxValidationError::UnexpectedPart);
            }
            if !matches!(
                entry.compression(),
                CompressionMethod::Stored | CompressionMethod::Deflated
            ) {
                return Err(DocxValidationError::UnsupportedCompression);
            }
            let size = entry.size();
            if size > self.limits.max_entry_uncompressed_bytes {
                return Err(DocxValidationError::LimitExceeded(DocxLimit::EntryBytes));
            }
            if exceeds_ratio(
                size,
                entry.compressed_size(),
                self.limits.max_compression_ratio,
            ) {
                return Err(DocxValidationError::LimitExceeded(
                    DocxLimit::CompressionRatio,
                ));
            }
            total = total
                .checked_add(size)
                .ok_or(DocxValidationError::LimitExceeded(DocxLimit::TotalBytes))?;
            if total > self.limits.max_total_uncompressed_bytes {
                return Err(DocxValidationError::LimitExceeded(DocxLimit::TotalBytes));
            }
            let capacity = usize::try_from(size)
                .map_err(|_| DocxValidationError::LimitExceeded(DocxLimit::EntryBytes))?;
            let mut value = Vec::with_capacity(capacity);
            let maximum = self
                .limits
                .max_entry_uncompressed_bytes
                .checked_add(1)
                .unwrap_or(u64::MAX);
            entry
                .by_ref()
                .take(maximum)
                .read_to_end(&mut value)
                .map_err(|_| DocxValidationError::InvalidZip)?;
            if u64::try_from(value.len()).unwrap_or(u64::MAX) != size {
                return Err(DocxValidationError::InvalidZip);
            }
            parts.insert(name, value);
        }
        Ok(parts)
    }
}

impl Default for DocxValidator {
    fn default() -> Self {
        Self::new(DocxLimits::default())
    }
}

fn validate_part_name(name: &str, limits: &DocxLimits) -> Result<String, DocxValidationError> {
    if name.is_empty()
        || name.len() > limits.max_part_name_bytes
        || name.starts_with('/')
        || name.starts_with('\\')
        || name.contains('\\')
        || name.contains(':')
        || name.contains('\0')
        || name
            .split('/')
            .any(|component| component.is_empty() || matches!(component, "." | ".."))
    {
        return Err(if name.len() > limits.max_part_name_bytes {
            DocxValidationError::LimitExceeded(DocxLimit::PartNameBytes)
        } else {
            DocxValidationError::UnsafePartName
        });
    }
    Ok(name.to_owned())
}

fn exceeds_ratio(uncompressed: u64, compressed: u64, maximum: u64) -> bool {
    if uncompressed == 0 {
        false
    } else if compressed == 0 {
        true
    } else {
        uncompressed > compressed.saturating_mul(maximum)
    }
}

fn validate_content_types(
    root: XmlNode,
    media: &BTreeMap<String, MediaTypeIr>,
) -> Result<(), DocxValidationError> {
    if !root.is(CONTENT_TYPES_NS, "Types") {
        return Err(DocxValidationError::InvalidContentTypes);
    }
    let mut rels = false;
    let mut xml = false;
    let mut png = false;
    let mut jpeg = false;
    let mut document = false;
    let mut keys = BTreeSet::new();
    for child in &root.children {
        if child.is(CONTENT_TYPES_NS, "Default") {
            let extension = required_attribute(child, "Extension")
                .ok_or(DocxValidationError::InvalidContentTypes)?;
            let content_type = required_attribute(child, "ContentType")
                .ok_or(DocxValidationError::InvalidContentTypes)?;
            if child.attributes.len() != 2 || !keys.insert(format!("default:{extension}")) {
                return Err(DocxValidationError::InvalidContentTypes);
            }
            match (extension, content_type) {
                ("rels", "application/vnd.openxmlformats-package.relationships+xml") => rels = true,
                ("xml", "application/xml") => xml = true,
                ("png", "image/png") => png = true,
                ("jpg", "image/jpeg") => jpeg = true,
                _ => return Err(DocxValidationError::InvalidContentTypes),
            }
        } else if child.is(CONTENT_TYPES_NS, "Override") {
            let part_name = required_attribute(child, "PartName")
                .ok_or(DocxValidationError::InvalidContentTypes)?;
            let content_type = required_attribute(child, "ContentType")
                .ok_or(DocxValidationError::InvalidContentTypes)?;
            if child.attributes.len() != 2
                || !keys.insert(format!("override:{part_name}"))
                || part_name != "/word/document.xml"
                || content_type != MAIN_CONTENT_TYPE
            {
                return Err(DocxValidationError::InvalidContentTypes);
            }
            document = true;
        } else {
            return Err(DocxValidationError::InvalidContentTypes);
        }
    }
    let needs_png = media.values().any(|value| *value == MediaTypeIr::Png);
    let needs_jpeg = media.values().any(|value| *value == MediaTypeIr::Jpeg);
    if rels && xml && document && png == needs_png && jpeg == needs_jpeg {
        Ok(())
    } else {
        Err(DocxValidationError::InvalidContentTypes)
    }
}

fn validate_root_relationships(root: XmlNode) -> Result<(), DocxValidationError> {
    if !root.is(PACKAGE_RELS_NS, "Relationships") || root.children.len() != 1 {
        return Err(DocxValidationError::InvalidRelationships);
    }
    let relationship = &root.children[0];
    if !relationship.is(PACKAGE_RELS_NS, "Relationship") {
        return Err(DocxValidationError::InvalidRelationships);
    }
    if relationship.attribute(None, "TargetMode") == Some("External") {
        return Err(DocxValidationError::ExternalRelationship);
    }
    if relationship.attributes.len() != 3
        || relationship.attribute(None, "Id") != Some("rId1")
        || relationship.attribute(None, "Type") != Some(OFFICE_DOCUMENT_REL)
        || relationship.attribute(None, "Target") != Some("word/document.xml")
    {
        return Err(DocxValidationError::InvalidRelationships);
    }
    Ok(())
}

fn validate_document_relationships(
    root: XmlNode,
    part_names: BTreeSet<&str>,
) -> Result<BTreeMap<String, String>, DocxValidationError> {
    if !root.is(PACKAGE_RELS_NS, "Relationships") {
        return Err(DocxValidationError::InvalidRelationships);
    }
    let mut relationships = BTreeMap::new();
    for relationship in &root.children {
        if !relationship.is(PACKAGE_RELS_NS, "Relationship") {
            return Err(DocxValidationError::InvalidRelationships);
        }
        if relationship.attribute(None, "TargetMode").is_some() {
            return Err(
                if relationship.attribute(None, "TargetMode") == Some("External") {
                    DocxValidationError::ExternalRelationship
                } else {
                    DocxValidationError::InvalidRelationships
                },
            );
        }
        if relationship.attributes.len() != 3
            || relationship.attribute(None, "Type") != Some(IMAGE_REL)
        {
            return Err(DocxValidationError::InvalidRelationships);
        }
        let id = relationship
            .attribute(None, "Id")
            .ok_or(DocxValidationError::InvalidRelationships)?;
        let target = relationship
            .attribute(None, "Target")
            .ok_or(DocxValidationError::InvalidRelationships)?;
        if !safe_relationship_target(target) {
            return Err(DocxValidationError::InvalidRelationships);
        }
        let resolved = format!("word/{target}");
        if !part_names.contains(resolved.as_str()) {
            return Err(DocxValidationError::BrokenRelationship);
        }
        if relationships.insert(id.to_owned(), resolved).is_some() {
            return Err(DocxValidationError::InvalidRelationships);
        }
    }
    Ok(relationships)
}

fn validate_document(
    root: XmlNode,
    images_expected: bool,
    limits: &DocxLimits,
) -> Result<BTreeSet<String>, DocxValidationError> {
    if !root.is(WORD_NS, "document") || root.children.len() != 1 {
        return Err(DocxValidationError::InvalidDocumentXml);
    }
    let body = &root.children[0];
    if !body.is(WORD_NS, "body") {
        return Err(DocxValidationError::InvalidDocumentXml);
    }
    let block_count = body.children.len().saturating_sub(1);
    if block_count > limits.max_blocks {
        return Err(DocxValidationError::LimitExceeded(DocxLimit::Blocks));
    }
    let Some(section) = body.children.last() else {
        return Err(DocxValidationError::InvalidDocumentXml);
    };
    if body.children[..body.children.len() - 1]
        .iter()
        .any(|child| !child.is(WORD_NS, "p"))
    {
        return Err(DocxValidationError::InvalidDocumentXml);
    }
    if !section.is(WORD_NS, "sectPr") || section.children.len() != 2 {
        return Err(DocxValidationError::InvalidDocumentXml);
    }
    if !section.children[0].is(WORD_NS, "pgSz") || !section.children[1].is(WORD_NS, "pgMar") {
        return Err(DocxValidationError::InvalidDocumentXml);
    }
    validate_page_properties(&section.children[0], &section.children[1])?;
    let mut descendants = Vec::new();
    root.descendants(&mut descendants);
    let mut drawing_ids = BTreeSet::new();
    let mut references = BTreeSet::new();
    let mut paragraphs = 0_usize;
    let mut runs = 0_usize;
    for node in descendants {
        if node.is(WORD_NS, "altChunk")
            || node.is(WORD_NS, "object")
            || node.is(WORD_NS, "pict")
            || node.is(WORD_NS, "binData")
        {
            return Err(DocxValidationError::ForbiddenContent);
        }
        if !allowed_document_element(node) {
            return Err(DocxValidationError::InvalidDocumentXml);
        }
        if !node.is(WORD_NS, "t") && !node.is(OFFICE_MATH_NS, "t") && !node.text.trim().is_empty() {
            return Err(DocxValidationError::InvalidDocumentXml);
        }
        if node.is(WORD_NS, "p") {
            paragraphs = paragraphs
                .checked_add(1)
                .ok_or(DocxValidationError::LimitExceeded(DocxLimit::Paragraphs))?;
            if paragraphs > limits.max_paragraphs {
                return Err(DocxValidationError::LimitExceeded(DocxLimit::Paragraphs));
            }
            if !valid_paragraph_children(node) {
                return if paragraphs > limits.max_paragraphs {
                    Err(DocxValidationError::LimitExceeded(DocxLimit::Paragraphs))
                } else {
                    Err(DocxValidationError::InvalidDocumentXml)
                };
            }
            if let Some(math) = node.children.first().filter(|_| node.children.len() == 1) {
                if math.is(OFFICE_MATH_NS, "oMath") {
                    validate_o_math(math, limits)?;
                } else if math.is(OFFICE_MATH_NS, "oMathPara") {
                    validate_o_math_para(math, limits)?;
                }
            }
        }
        if node.is(WORD_NS, "r") {
            runs = runs
                .checked_add(1)
                .ok_or(DocxValidationError::LimitExceeded(DocxLimit::Runs))?;
            if runs > limits.max_runs {
                return Err(DocxValidationError::LimitExceeded(DocxLimit::Runs));
            }
            validate_run(node)?;
        }
        if node.is(WORD_DRAWING_NS, "docPr") {
            let id = node
                .attribute(None, "id")
                .and_then(|value| value.parse::<u32>().ok())
                .filter(|value| *value != 0)
                .ok_or(DocxValidationError::InvalidDocumentXml)?;
            if !drawing_ids.insert(id) {
                return Err(DocxValidationError::DuplicateDrawingId);
            }
        }
        if node.is(DRAWING_NS, "blip") {
            let relationship = node
                .attribute(Some(DRAWING_REL_NS), "embed")
                .ok_or(DocxValidationError::InvalidDocumentXml)?;
            if !references.insert(relationship.to_owned()) {
                return Err(DocxValidationError::ImageMismatch);
            }
        }
    }
    if images_expected == references.is_empty() || drawing_ids.len() != references.len() {
        return Err(DocxValidationError::ImageMismatch);
    }
    Ok(references)
}

fn validate_page_properties(
    page_size: &XmlNode,
    page_margins: &XmlNode,
) -> Result<(), DocxValidationError> {
    let width = numeric_word_attribute(page_size, "w")?;
    let height = numeric_word_attribute(page_size, "h")?;
    if width == 0 || height == 0 {
        return Err(DocxValidationError::InvalidDocumentXml);
    }
    let orientation = page_size.attribute(Some(WORD_NS), "orient");
    if !matches!(orientation, None | Some("landscape"))
        || page_size.attributes.len() != 2 + usize::from(orientation.is_some())
    {
        return Err(DocxValidationError::InvalidDocumentXml);
    }
    for name in ["top", "right", "bottom", "left"] {
        numeric_word_attribute(page_margins, name)?;
    }
    if page_margins.attributes.len() != 4 {
        return Err(DocxValidationError::InvalidDocumentXml);
    }
    Ok(())
}

fn numeric_word_attribute(node: &XmlNode, local: &str) -> Result<u64, DocxValidationError> {
    node.attribute(Some(WORD_NS), local)
        .and_then(|value| value.parse().ok())
        .ok_or(DocxValidationError::InvalidDocumentXml)
}

fn validate_run(run: &XmlNode) -> Result<(), DocxValidationError> {
    if run.children.is_empty()
        || run.children.iter().any(|child| {
            !child.is(WORD_NS, "rPr") && !child.is(WORD_NS, "t") && !child.is(WORD_NS, "drawing")
        })
        || run
            .children
            .iter()
            .filter(|child| child.is(WORD_NS, "rPr"))
            .count()
            > 1
        || run
            .children
            .iter()
            .filter(|child| child.is(WORD_NS, "t") || child.is(WORD_NS, "drawing"))
            .count()
            != 1
        || run
            .children
            .iter()
            .position(|child| child.is(WORD_NS, "rPr"))
            .is_some_and(|position| position != 0)
    {
        return Err(DocxValidationError::InvalidDocumentXml);
    }
    Ok(())
}

fn allowed_document_element(node: &XmlNode) -> bool {
    match node.namespace.as_deref() {
        Some(WORD_NS) => matches!(
            node.local.as_str(),
            "document"
                | "body"
                | "p"
                | "r"
                | "rPr"
                | "b"
                | "i"
                | "u"
                | "strike"
                | "vertAlign"
                | "rFonts"
                | "sz"
                | "color"
                | "t"
                | "drawing"
                | "sectPr"
                | "pgSz"
                | "pgMar"
        ),
        Some(WORD_DRAWING_NS) => matches!(
            node.local.as_str(),
            "inline" | "extent" | "effectExtent" | "docPr" | "cNvGraphicFramePr"
        ),
        Some(DRAWING_NS) => matches!(
            node.local.as_str(),
            "extLst"
                | "graphicFrameLocks"
                | "graphic"
                | "graphicData"
                | "blip"
                | "stretch"
                | "fillRect"
                | "xfrm"
                | "off"
                | "ext"
                | "prstGeom"
                | "avLst"
        ),
        Some(PICTURE_NS) => matches!(
            node.local.as_str(),
            "pic" | "nvPicPr" | "cNvPr" | "cNvPicPr" | "blipFill" | "spPr"
        ),
        Some(OFFICE_MATH_NS) => matches!(
            node.local.as_str(),
            "oMath"
                | "oMathPara"
                | "r"
                | "rPr"
                | "sty"
                | "t"
                | "f"
                | "fPr"
                | "type"
                | "num"
                | "den"
        ),
        _ => false,
    }
}

fn valid_paragraph_children(paragraph: &XmlNode) -> bool {
    paragraph
        .children
        .iter()
        .all(|child| child.is(WORD_NS, "r"))
        || (paragraph.children.len() == 1
            && (paragraph.children[0].is(OFFICE_MATH_NS, "oMath")
                || paragraph.children[0].is(OFFICE_MATH_NS, "oMathPara")))
}

fn validate_o_math_para(node: &XmlNode, limits: &DocxLimits) -> Result<(), DocxValidationError> {
    if !node.attributes.is_empty()
        || !node.text.trim().is_empty()
        || node.children.len() != 1
        || !node.children[0].is(OFFICE_MATH_NS, "oMath")
    {
        return Err(DocxValidationError::InvalidEquation);
    }
    validate_o_math(&node.children[0], limits)
}

fn validate_o_math(node: &XmlNode, limits: &DocxLimits) -> Result<(), DocxValidationError> {
    if !node.attributes.is_empty() || !node.text.trim().is_empty() || node.children.is_empty() {
        return Err(DocxValidationError::InvalidEquation);
    }
    let source_bytes = node.source_end.saturating_sub(node.source_start);
    if u64::try_from(source_bytes).unwrap_or(u64::MAX) > limits.max_equation_output_bytes {
        return Err(DocxValidationError::LimitExceeded(
            DocxLimit::EquationOutputBytes,
        ));
    }
    let mut state = EquationValidationState { nodes: 0, limits };
    validate_math_sequence(&node.children, 0, &mut state)
}

struct EquationValidationState<'a> {
    nodes: usize,
    limits: &'a DocxLimits,
}

impl EquationValidationState<'_> {
    fn count_node(&mut self, depth: usize) -> Result<(), DocxValidationError> {
        if depth > self.limits.max_equation_depth {
            return Err(DocxValidationError::LimitExceeded(DocxLimit::EquationDepth));
        }
        self.nodes = self
            .nodes
            .checked_add(1)
            .ok_or(DocxValidationError::LimitExceeded(DocxLimit::EquationNodes))?;
        if self.nodes > self.limits.max_equation_nodes {
            return Err(DocxValidationError::LimitExceeded(DocxLimit::EquationNodes));
        }
        Ok(())
    }
}

fn validate_math_sequence(
    children: &[XmlNode],
    depth: usize,
    state: &mut EquationValidationState<'_>,
) -> Result<(), DocxValidationError> {
    if children.is_empty() {
        return Err(DocxValidationError::InvalidEquation);
    }
    for child in children {
        state.count_node(depth)?;
        if child.is(OFFICE_MATH_NS, "r") {
            validate_math_run(child)?;
        } else if child.is(OFFICE_MATH_NS, "f") {
            validate_fraction(child, depth, state)?;
        } else {
            return Err(DocxValidationError::InvalidEquation);
        }
    }
    Ok(())
}

fn validate_math_run(node: &XmlNode) -> Result<(), DocxValidationError> {
    let valid_shape = match node.children.as_slice() {
        [text] => text.is(OFFICE_MATH_NS, "t"),
        [_, text] => text.is(OFFICE_MATH_NS, "t"),
        _ => false,
    };
    if !node.attributes.is_empty() || !node.text.trim().is_empty() || !valid_shape {
        return Err(DocxValidationError::InvalidEquation);
    }
    if node.children.len() == 2 {
        let properties = &node.children[0];
        if !properties.is(OFFICE_MATH_NS, "rPr")
            || !properties.attributes.is_empty()
            || !properties.text.trim().is_empty()
            || properties.children.len() != 1
        {
            return Err(DocxValidationError::InvalidEquation);
        }
        let style = &properties.children[0];
        if !style.is(OFFICE_MATH_NS, "sty")
            || style.attributes.len() != 1
            || style.attribute(Some(OFFICE_MATH_NS), "val") != Some("i")
            || !style.children.is_empty()
            || !style.text.trim().is_empty()
        {
            return Err(DocxValidationError::InvalidEquation);
        }
    }
    let text = node
        .children
        .last()
        .ok_or(DocxValidationError::InvalidEquation)?;
    if !text.attributes.is_empty()
        && (text.attributes.len() != 1
            || text.attribute(Some("http://www.w3.org/XML/1998/namespace"), "space")
                != Some("preserve"))
    {
        return Err(DocxValidationError::InvalidEquation);
    }
    if !text.children.is_empty() {
        return Err(DocxValidationError::InvalidEquation);
    }
    if text.text.is_empty() {
        return Err(DocxValidationError::InvalidEquation);
    }
    Ok(())
}

fn validate_fraction(
    node: &XmlNode,
    depth: usize,
    state: &mut EquationValidationState<'_>,
) -> Result<(), DocxValidationError> {
    if !node.attributes.is_empty() || !node.text.trim().is_empty() || node.children.len() != 3 {
        return Err(DocxValidationError::InvalidEquation);
    }
    let properties = &node.children[0];
    let numerator = &node.children[1];
    let denominator = &node.children[2];
    if !properties.is(OFFICE_MATH_NS, "fPr")
        || !properties.attributes.is_empty()
        || !properties.text.trim().is_empty()
        || properties.children.len() != 1
        || !properties.children[0].is(OFFICE_MATH_NS, "type")
        || properties.children[0].attributes.len() != 1
        || properties.children[0].attribute(Some(OFFICE_MATH_NS), "val") != Some("bar")
        || !properties.children[0].children.is_empty()
        || !properties.children[0].text.trim().is_empty()
        || !numerator.is(OFFICE_MATH_NS, "num")
        || !numerator.attributes.is_empty()
        || !numerator.text.trim().is_empty()
        || !denominator.is(OFFICE_MATH_NS, "den")
        || !denominator.attributes.is_empty()
        || !denominator.text.trim().is_empty()
    {
        return Err(DocxValidationError::InvalidEquation);
    }
    let next_depth = depth
        .checked_add(1)
        .ok_or(DocxValidationError::LimitExceeded(DocxLimit::EquationDepth))?;
    validate_math_sequence(&numerator.children, next_depth, state)?;
    validate_math_sequence(&denominator.children, next_depth, state)
}

fn required_attribute<'a>(node: &'a XmlNode, local: &str) -> Option<&'a str> {
    node.attribute(None, local)
}

fn classify_unexpected(name: &str) -> DocxValidationError {
    let folded = name.to_ascii_lowercase();
    if folded.ends_with("vbaproject.bin")
        || folded.contains("embeddings/")
        || folded.ends_with(".ole")
        || folded.ends_with(".html")
        || folded.ends_with(".htm")
    {
        DocxValidationError::ForbiddenContent
    } else {
        DocxValidationError::UnexpectedPart
    }
}

fn media_part_type(name: &str) -> Option<MediaTypeIr> {
    let suffix = name.strip_prefix("word/media/image")?;
    let (number, extension) = suffix.rsplit_once('.')?;
    if number.is_empty()
        || number.starts_with('0')
        || !number.bytes().all(|byte| byte.is_ascii_digit())
        || number.parse::<u32>().ok()? == 0
    {
        return None;
    }
    match extension {
        "png" => Some(MediaTypeIr::Png),
        "jpg" => Some(MediaTypeIr::Jpeg),
        _ => None,
    }
}

fn safe_relationship_target(target: &str) -> bool {
    !target.is_empty()
        && !target.starts_with('/')
        && !target.starts_with('\\')
        && !target.contains('\\')
        && !target.contains(':')
        && !target.contains('?')
        && !target.contains('#')
        && target
            .split('/')
            .all(|component| !component.is_empty() && !matches!(component, "." | ".."))
        && media_part_type(&format!("word/{target}")).is_some()
}
