[package]
name = "mathcad-parser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
math-model = { path = "../math-model" }
quick-xml = { version = "=0.41.0", default-features = false }
thiserror = "=2.0.17"
zip = { version = "=8.6.0", default-features = false, features = ["deflate-flate2-zlib-rs"] }
